### PR TITLE
fix(dapp): fetch display for auctions

### LINKED ISSUE #535: Infinite loading of display image for auctions
Currently in the `dapp` the auctions are not able to resolve the display image through the logic in `AvatarDisplay`

Solve this by calling the `names-display` directly

- Add an `ENV` variable to configure the names-display API base URL
- Add a hook to fetch an image based on name and expirationDate
- Use this hooks in the places where we render auction "NameCard"(s)

### PR DESCRIPTION
**Pull request by KeitoTadashi**
fixes #535

### CODE REVIEW

File: dapp/src/auctions/hooks/useAuctionDisplayImages.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
+// Copyright (c) 2025 IOTA Stiftung
+// SPDX-License-Identifier: Apache-2.0
+
+import { useQuery } from '@tanstack/react-query';
+
+export function useAuctionDisplayImages(name: string, expirationTimestamp: string) {
```
Comment (VmMad) [inline dapp/src/auctions/hooks/useAuctionDisplayImages.ts]:
```suggestion
export function useAuctionDisplayImage(name: string, expirationTimestamp: string) {
```

File: dapp/src/auctions/hooks/useAuctionDisplayImages.ts
Comment (VmMad) [inline dapp/src/auctions/hooks/useAuctionDisplayImages.ts:1]: wouldn't it be better to just create a function to get the url and then pass it to an `` directly ?

File: dapp/src/components/name-card/NameCard.tsx [hunk 2]
```diff
@@ -35,6 +37,7 @@ export function NameCard({
                 size={size}
                 badge={badge}
                 button={menuOptions ? <ContextMenuButton options={menuOptions} /> : null}
+                fallbackUrl={auctionDisplay}
```
Comment (VmMad) [inline dapp/src/components/name-card/NameCard.tsx]: i think it would be better to show add another prop to receive an static image url and render an `<img` based on that, so that we avoid trying to fetch registration data for bids just to try to load the image, which we know will return undefined.

Comment (VmMad) [reply dapp/src/components/name-card/NameCard.tsx]: this prop is used as a fallback if the avatar and image display are not available, so it would try to load both and at the end set this string, so i feel like it would be better to use another prop

File: dapp/next.config.mjs [hunk 3]
```diff
@@ -4,6 +4,7 @@
 import { execSync } from 'child_process';
 
 let NEXT_PUBLIC_IOTA_NAMES_REV = 'development';
+let NEXT_PUBLIC_NAMES_DISPLAY_API_URL = process.env.NEXT_PUBLIC_NAMES_DISPLAY_API_URL;
```
Comment (msarcev) [inline dapp/next.config.mjs]:
```suggestion
let NEXT_PUBLIC_NAMES_DISPLAY_API_URL = '';
```

File: dapp/src/app/(protected)/my-names/components/PanelTile.tsx [hunk 4]
```diff
@@ -57,7 +57,7 @@ export function PanelTile({
                                 type={ImageType.BgTransparent}
                                 shape={ImageShape.SquareRounded}
                             >
-                                <AvatarDisplay
+                                <NameCardDisplay
```
Comment (msarcev) [inline dapp/src/app/(protected)/my-names/components/PanelTile.tsx]: I don't think this needs to change.

File: dapp/src/auctions/hooks/useAuctionDisplayImage.ts [hunk 5]
```diff
@@ -0,0 +1,22 @@
+// Copyright (c) 2025 IOTA Stiftung
+// SPDX-License-Identifier: Apache-2.0
+
+import { useQuery } from '@tanstack/react-query';
+
+export function useAuctionDisplayImage(name: string, expirationTimestamp: string) {
+    return useQuery({
```
Comment (msarcev) [inline dapp/src/auctions/hooks/useAuctionDisplayImage.ts]: We probably don't need react query to build this string. A util function should be fine.

File: dapp/next.config.mjs [hunk 6]
```diff
@@ -15,10 +16,17 @@ try {
     console.warn('Could not get git revision, using default');
 }
 
+if (process.env.NEXT_PUBLIC_NAMES_DISPLAY_API_URL) {
+    NEXT_PUBLIC_NAMES_DISPLAY_API_URL = process.env.NEXT_PUBLIC_NAMES_DISPLAY_API_URL;
+} else {
+    throw new Error('NEXT_PUBLIC_NAMES_DISPLAY_API_URL env must be configured');
+}
+
```
Comment (VmMad) [inline dapp/next.config.mjs]: you've already created the `let` with the `.env`
```suggestion
if (!NEXT_PUBLIC_NAMES_DISPLAY_API_URL) {
    throw new Error('NEXT_PUBLIC_NAMES_DISPLAY_API_URL env must be configured');
}

```

File: dapp/src/components/name-record/NameCardDisplay.tsx
Comment (msarcev) [inline dapp/src/components/name-record/NameCardDisplay.tsx:1]: I don't think we need all these changes. We should probably leave `AvatarDisplay` unchanged.

File: dapp/src/components/name-card/NameCard.tsx [hunk 7]
```diff
@@ -30,11 +32,12 @@ export function NameCard({
                 nftDisplayVariants({ size }),
             )}
         >
-            <AvatarDisplay
+            <NameCardDisplay
```
Comment (msarcev) [inline dapp/src/components/name-card/NameCard.tsx]: Instead of doing this `NamesDisplay` changes. Just handle it here
```
auctionDisplay ? <img .... > : <AvatarDisplay .... />
```

**Review by msarcev — CHANGES_REQUESTED** [review]

File: dapp/src/auctions/hooks/useAuctionDisplayImage.ts [hunk 8]
```diff
@@ -0,0 +1,22 @@
...
+            }
+            const url = `${baseUrl}/${name}/${expirationTimestamp}`;
+            return {
+                url,
+            };
+        },
+        enabled: !!name && !!expirationTimestamp,
+        gcTime: 0,
+    });
+}
```
Comment (VmMad) [inline dapp/src/auctions/hooks/useAuctionDisplayImage.ts]: There's no real benefit of doing this as a query, its better to do a function instead. 
Also the env should already be defined at this point

```ts
function getNameDisplaySrc(name, expirationTimestamp) {
    const baseUrl = process.env.NEXT_PUBLIC_NAMES_DISPLAY_API_URL;
    return new URL(`${name}/${expirationTimestamp}`, baseUrl).href;
}
```

File: dapp/src/components/name-card/NameCard.tsx [hunk 9]
```diff
@@ -30,11 +32,12 @@ export function NameCard({
...
                 name={name}
                 size={size}
                 badge={badge}
                 button={menuOptions ? <ContextMenuButton options={menuOptions} /> : null}
+                fallbackUrl={auctionDisplay}
```
Comment (VmMad) [inline dapp/src/components/name-card/NameCard.tsx]: if we dont use `staticImageSrc` then the component will go through the avatar route and execute unnecessary hooks
```suggestion
                staticImageSrc={auctionDisplay}
```

File: dapp/src/components/name-card/NameCard.tsx [hunk 10]
```diff
@@ -7,11 +7,12 @@ import { nftDisplayVariants } from '@/components/name-record/variants';
 import { MenuListItem, type NftDisplayProps } from '@/lib/types/components';
 
 import { ContextMenuButton } from '../buttons/ContextMenuButton';
-import { AvatarDisplay } from '../name-record/AvatarDisplay';
+import { NameCardDisplay } from '../name-record/NameCardDisplay';
 
 interface NameCardProps extends NftDisplayProps {
     menuOptions?: MenuListItem[];
     isSelected?: boolean;
+    auctionDisplay?: string;
```
Comment (VmMad) [inline dapp/src/components/name-card/NameCard.tsx]: this prop can be agnostic to `auction`, so i'd change it to something like `displaySrc`

**Review by VmMad — DISMISSED** [review]
Lint is failing 🙏🏽

File: dapp/src/components/name-record/NameCardDisplay.tsx
Comment (VmMad) [reply dapp/src/components/name-record/NameCardDisplay.tsx:1]: I suggested this change. This was so that if you passed a `staticImageSrc` it didn't need to load or fetch any unnecessary things e.g (useRegistrationNfts inside the avatarDisplay). But you're correct it can be handled from outside

File: dapp/src/components/name-card/NameCard.tsx (hunk 7 above)
Comment (VmMad) [reply dapp/src/components/name-card/NameCard.tsx]: or yes... this could be a solution too. handling from here and leaving the AvatarDisplay as it was

File: dapp/src/components/name-record/AvatarDisplay.tsx [hunk 11]
```diff
@@ -15,38 +14,40 @@ import { nftDisplayVariants } from './variants';
...
 }
 
-export function AvatarDisplay({ name, size, badge, button, fallbackUrl }: AvatarDisplayProps) {
+export function AvatarDisplay({
+    name,
+    size,
+    badge,
+    button,
+    fallbackUrl,
+    staticImageSrc,
```
Comment (msarcev) [inline dapp/src/components/name-record/AvatarDisplay.tsx]: I don't see why this is needed ? 
@VmMad what was your idea ?

**Review by msarcev — APPROVED** [review]

**Review by marc2332 — APPROVED** [review]
