### PR TITLE
fix: Fix retry loop in worker

### LINKED ISSUE #232: indexer: stop if there is an error instead of trying to process a checkpoint in an endless loop
## Description

If there was an error in `process_checkpoint()` the indexer should be stopped

## Motivation

If it's not stopped, it will try to process the checkpoint again, just to fail again

```
2025-06-02T13:33:31.558423Z DEBUG iota_names_indexer::worker: Processing checkpoint: 217
2025-06-02T13:33:31.558661Z DEBUG iota_names_indexer::worker: Processing checkpoint: 218
2025-06-02T13:33:31.558974Z DEBUG iota_names_indexer::worker: Processing checkpoint: 219
2025-06-02T13:33:31.698109Z DEBUG iota_names_indexer::worker: Processing checkpoint: 220
2025-06-02T13:33:31.698535Z DEBUG iota_names_indexer::worker: Processing checkpoint: 221
2025-06-02T13:33:31.698799Z DEBUG iota_names_indexer::worker: Processing checkpoint: 222
2025-06-02T13:33:31.699100Z DEBUG iota_names_indexer::worker: Processing checkpoint: 223
2025-06-02T13:33:31.699496Z DEBUG iota_names_indexer::worker: Processing checkpoint: 224
Found balance object: Object(ObjectInner { data: Move(MoveObject { type_: MoveObjectType(Other(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("dynamic_field"), name: Identifier("Field"), type_params: [Struct(StructTag { address: a0626c2331fcd84b99646151216915e46c4468053b600001c6230cad092755b1, module: Identifier("iota_names"), name: Identifier("BalanceKey"), type_params: [Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("iota"), name: Identifier("IOTA"), type_params: [] })] }), Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("balance"), name: Identifier("Balance"), type_params: [Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("iota"), name: Identifier("IOTA"), type_params: [] })] })] })), version: SequenceNumber(891), contents: [17, 78, 49, 254, 188, 5, 196, 16, 44, 220, 40, 161, 69, 238, 12, 230, 2, 62, 240, 27, 40, 252, 207, 176, 122, 117, 217, 112, 199, 137, 230, 101, 0, 0, 101, 205, 29, 0, 0, 0, 0] }), owner: ObjectOwner(0xce007c84a87e7c3b6f6b2f06917d437f5184f310cd8ef3bcb28ff9b7874afb74), previous_transaction: TransactionDigest(Dbmjb3Rsf69VptzkqxwZDtqAjSB64b6mzmQNbA6XdYim), storage_rebate: 2865200 })
2025-06-02T13:33:32.326990Z DEBUG iota_names_indexer::worker: Processing checkpoint: 224
Found balance object: Object(ObjectInner { data: Move(MoveObject { type_: MoveObjectType(Other(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("dynamic_field"), name: Identifier("Field"), type_params: [Struct(StructTag { address: a0626c2331fcd84b99646151216915e46c4468053b600001c6230cad092755b1, module: Identifier("iota_names"), name: Identifier("BalanceKey"), type_params: [Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("iota"), name: Identifier("IOTA"), type_params: [] })] }), Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("balance"), name: Identifier("Balance"), type_params: [Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("iota"), name: Identifier("IOTA"), type_params: [] })] })] })), version: SequenceNumber(891), contents: [17, 78, 49, 254, 188, 5, 196, 16, 44, 220, 40, 161, 69, 238, 12, 230, 2, 62, 240, 27, 40, 252, 207, 176, 122, 117, 217, 112, 199, 137, 230, 101, 0, 0, 101, 205, 29, 0, 0, 0, 0] }), owner: ObjectOwner(0xce007c84a87e7c3b6f6b2f06917d437f5184f310cd8ef3bcb28ff9b7874afb74), previous_transaction: TransactionDigest(Dbmjb3Rsf69VptzkqxwZDtqAjSB64b6mzmQNbA6XdYim), storage_rebate: 2865200 })
2025-06-02T13:33:32.728735Z DEBUG iota_names_indexer::worker: Processing checkpoint: 224
Found balance object: Object(ObjectInner { data: Move(MoveObject { type_: MoveObjectType(Other(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("dynamic_field"), name: Identifier("Field"), type_params: [Struct(StructTag { address: a0626c2331fcd84b99646151216915e46c4468053b600001c6230cad092755b1, module: Identifier("iota_names"), name: Identifier("BalanceKey"), type_params: [Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("iota"), name: Identifier("IOTA"), type_params: [] })] }), Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("balance"), name: Identifier("Balance"), type_params: [Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("iota"), name: Identifier("IOTA"), type_params: [] })] })] })), version: SequenceNumber(891), contents: [17, 78, 49, 254, 188, 5, 196, 16, 44, 220, 40, 161, 69, 238, 12, 230, 2, 62, 240, 27, 40, 252, 207, 176, 122, 117, 217, 112, 199, 137, 230, 101, 0, 0, 101, 205, 29, 0, 0, 0, 0] }), owner: ObjectOwner(0xce007c84a87e7c3b6f6b2f06917d437f5184f310cd8ef3bcb28ff9b7874afb74), previous_transaction: TransactionDigest(Dbmjb3Rsf69VptzkqxwZDtqAjSB64b6mzmQNbA6XdYim), storage_rebate: 2865200 })
2025-06-02T13:33:34.189915Z DEBUG iota_names_indexer::worker: Processing checkpoint: 224
Found balance object: Object(ObjectInner { data: Move(MoveObject { type_: MoveObjectType(Other(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("dynamic_field"), name: Identifier("Field"), type_params: [Struct(StructTag { address: a0626c2331fcd84b99646151216915e46c4468053b600001c6230cad092755b1, module: Identifier("iota_names"), name: Identifier("BalanceKey"), type_params: [Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("iota"), name: Identifier("IOTA"), type_params: [] })] }), Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("balance"), name: Identifier("Balance"), type_params: [Struct(StructTag { address: 0000000000000000000000000000000000000000000000000000000000000002, module: Identifier("iota"), name: Identifier("IOTA"), type_params: [] })] })] })), version: SequenceNumber(891), contents: [17, 78, 49, 254, 188, 5, 196, 16, 44, 220, 40, 161, 69, 238, 12, 230, 2, 62, 240, 27, 40, 252, 207, 176, 122, 117, 217, 112, 199, 137, 230, 101, 0, 0, 101, 205, 29, 0, 0, 0, 0] }), owner: ObjectOwner(0xce007c84a87e7c3b6f6b2f06917d437f5184f310cd8ef3bcb28ff9b7874afb74), previous_transaction: TransactionDigest(Dbmjb3Rsf69VptzkqxwZDtqAjSB64b6mzmQNbA6XdYim), storage_rebate: 2865200 })
2025-06-02T13:33:36.410136Z DEBUG iota_names_indexer::worker: Processing checkpoint: 224
...
```

### PR DESCRIPTION
**Pull request by DaughterOfMars**
## Description

Fixes an issue where the worker would just retry over and over on an error.

Fixes #232

### CODE REVIEW

File: indexer/src/worker.rs [hunk 1]
```diff
@@ -107,17 +115,8 @@ impl IotaNamesWorker {
...
-#[async_trait]
-impl Worker for IotaNamesWorker {
-    type Message = ();
-    type Error = anyhow::Error;
 
-    async fn process_checkpoint(
-        &self,
-        checkpoint: Arc<CheckpointData>, // TODO change to &?
-    ) -> Result<Self::Message, Self::Error> {
+    async fn process_checkpoint(&self, checkpoint: &CheckpointData) -> anyhow::Result<()> {
```
Comment (thibault-martinez) [inline indexer/src/worker.rs:120]: Why the non-trait method?

**Review by Alex6323 — APPROVED** [review]

File: indexer/src/worker.rs (hunk 1 above)
Comment (DaughterOfMars) [reply indexer/src/worker.rs:120]: Just to wrap it easily really

**Review by Thoralf-M — CHANGES_REQUESTED** [review]
It works fine if there was an error, but it still loops if there was a panic

Error working:
```
2025-06-03T12:11:33.829513Z DEBUG iota_names_indexer::worker: Processing checkpoint: 100
2025-06-03T12:11:33.829822Z ERROR iota_names_indexer::worker: test error
2025-06-03T12:11:33.829874Z  WARN iota_data_ingestion_core::worker_pool: transient worker execution error CheckpointProcessing("test error") for checkpoint 100
2025-06-03T12:11:33.830041Z  INFO iota_data_ingestion_core::worker_pool: Worker pool `iota_names_reader` terminated gracefully
2025-06-03T12:11:33.830087Z  INFO iota_names_indexer: runtime stopped
2025-06-03T12:11:33.831108Z  INFO iota_data_ingestion_core::reader: remote reader dropped
```

panic not working
```
2025-06-03T12:12:58.855002Z DEBUG iota_names_indexer::worker: Processing checkpoint: 100
2025-06-03T12:12:58.855274Z ERROR iota_names_indexer: panicked at src/worker.rs:160:9:
test panic
2025-06-03T12:12:58.956249Z DEBUG iota_data_ingestion_core::reader: unprocessed local files []
2025-06-03T12:12:58.956320Z  INFO iota_data_ingestion_core::reader: Read from remote. Current checkpoint number: 110, pruning watermark: 100, new updates: 10
2025-06-03T12:12:59.057210Z DEBUG iota_data_ingestion_core::reader: unprocessed local files []
2025-06-03T12:12:59.057273Z  INFO iota_data_ingestion_core::reader: Read from remote. Current checkpoint number: 120, pruning watermark: 100, new updates: 10
2025-06-03T12:12:59.158257Z DEBUG iota_data_ingestion_core::reader: unprocessed local files []
2025-06-03T12:12:59.158321Z  INFO iota_data_ingestion_core::reader: Read from remote. Current checkpoint number: 130, pruning watermark: 100, new updates: 10
```

**Comment by DaughterOfMars** [comment]
Fixed the panic issue by catching them. Tested by panicking manually:

```
2025-06-04 09:36:43 2025-06-04T07:36:43.040851Z  INFO iota_names_indexer: Starting IOTA Names Indexer
2025-06-04 09:36:43 2025-06-04T07:36:43.041472Z  INFO iota_names_indexer::metrics: Starting prometheus metrics at 0.0.0.0:9184
2025-06-04 09:36:43 2025-06-04T07:36:43.042378Z  INFO iota_names_indexer::worker: Connecting to node at http://host.docker.internal:9000
2025-06-04 09:36:43 2025-06-04T07:36:43.300999Z DEBUG iota_names_indexer::worker: Processing checkpoint: 0
2025-06-04 09:36:43 2025-06-04T07:36:43.301158Z ERROR iota_names_indexer: panicked at src/worker.rs:144:9:
2025-06-04 09:36:43 test
2025-06-04 09:36:43 2025-06-04T07:36:43.301381Z ERROR iota_names_indexer::worker: test
2025-06-04 09:36:43 2025-06-04T07:36:43.301582Z  INFO iota_names_indexer: runtime stopped
```

**Review by Thoralf-M — APPROVED** [review]

**Review by Alex6323 — APPROVED** [review]

File: indexer/src/worker.rs (hunk 1 above)
Comment (thibault-martinez) [reply indexer/src/worker.rs:120]: I fail to see how this is any easier, seems verbose and not really necessary. Couldn't it just have been a scope/closure in the main method?

**Review by thibault-martinez — APPROVED** [review]

File: indexer/src/worker.rs (hunk 1 above)
Comment (DaughterOfMars) [reply indexer/src/worker.rs:120]: No, because we don't call this fn

Comment (thibault-martinez) [reply indexer/src/worker.rs:120]: Not sure what you mean, but feel free to merge
