### PR TITLE
fix(ts-sdk): add retries when fetching balance data

### LINKED ISSUE #1045: Fix flaky ts-sdk tests
See https://github.com/iotaledger/iota-names/actions/runs/20785504833/job/59693784275
This issue seems to pop from time to time

### PR DESCRIPTION
**Pull request by VmMad**
Fixes #1045

Balance is probably not propagated since the faucet is correctly requested, so we need to give some time

A run that would have failed without the fix: https://github.com/iotaledger/iota-names/actions/runs/21175631179/job/61008204575#step:11:303

### CODE REVIEW

File: sdk/test/toolbox.ts [hunk 1]
```diff
@@ -71,9 +71,18 @@ export async function setupIotaClient() {
...
-        owner: address,
-    });
+    const b = await retry(
+        () =>
+            client.getBalance({
+                owner: address,
+            }),
+        {
+            retries: 10,
+            delay: 1000,
```
Comment (Thoralf-M) [inline sdk/test/toolbox.ts]: Would rather do something like this, 1 second delay is pretty long
```suggestion
            retries: 100,
            delay: 50,
```

**Review by Thoralf-M — APPROVED** [review]

**Review by KeitoTadashi — APPROVED** [review]
