### PR TITLE
fix(scripts): validate labels and names before publish, split label txs

### LINKED ISSUE #525: Split labels to block/reserve into multiple txs if needed
## Description

Currently when trying to block and reserve many names, it would fail:
```
Blocking 919 labels
Reserving 3234 labels
/home/t/iota-names/node_modules/.pnpm/@iota+iota-sdk@0.0.0-experimental-20250611113155_typescript@5.8.3/node_modules/@iota/iota-sdk/src/client/http-transport.ts:122
            throw new JsonRpcError(data.error.message, data.error.code);
                  ^
JsonRpcError: Error checking transaction input objects: SizeLimitExceeded { limit: "maximum pure argument size", value: "16384" }
```

### PR DESCRIPTION
**Pull request by Thoralf-M**
Validate labels and names before publishing the packages, to avoid potential manual actions after the packages were published for the case that the lists contain invalid labels.
Automatically remove duplicated labels and convert upper case entries to lowercase
Also split the labels to block/reserve into batches, to prevent exceeding the protocol limits for transactions

Fixes https://github.com/iotaledger/iota-names/issues/525
Tested locally by running the init script with large (over 3k) labels in the list so they had to be split into multiple txs

### CODE REVIEW

File: scripts/reserved-names/deny-labels.ts [hunk 1]
```diff
@@ -59,37 +69,72 @@ export const addReservedLabels = (
...
-
-    return hasLabels;
-};
+    if (batch.length > 0) {
+        const tx = new Transaction();
+        console.log(`${action === 'block' ? 'Blocking' : 'Reserving'} ${batch.length} labels`);
+        processLabelsBatch(tx, packageInfo, action, batch);
+        const result = await signAndExecute(tx, network);
+        await client.waitForTransaction({ digest: result.digest });
+        console.log(`Transaction digest: ${result.digest}`);
```
Comment (DaughterOfMars) [inline scripts/reserved-names/deny-labels.ts]: Maybe put this in a fn to dedup?

File: scripts/reserved-names/deny-labels.ts [hunk 2]
```diff
@@ -59,37 +69,72 @@ export const addReservedLabels = (
...
+    packageInfo: PackageInfoForLabels,
+    action: 'block' | 'reserve',
+    labels: string[],
+): void {
+    const { packageId, iotaNamesObjectId, adminCap } = packageInfo;
+    if (action === 'block') {
+        addBlockedLabels(tx, packageId, iotaNamesObjectId, adminCap, labels);
+    } else {
+        addReservedLabels(tx, packageId, iotaNamesObjectId, adminCap, labels);
+    }
```
Comment (Alex6323) [inline scripts/reserved-names/deny-labels.ts:102]: maybe better to throw an error if the action is neither `block` nor `reserve`, or is TS already catching that?

Comment (DaughterOfMars) [reply scripts/reserved-names/deny-labels.ts:102]: typescript validates this at build time I believe

**Review by Alex6323 — APPROVED** [review]

File: scripts/reserved-names/deny-labels.ts (hunk 1 above)
Comment (Thoralf-M) [reply scripts/reserved-names/deny-labels.ts]: https://github.com/iotaledger/iota-names/pull/527/commits/df04973c44095965db967c98bcb8ca5b55a979d2

**Review by DaughterOfMars — APPROVED** [review]
