### PR TITLE
fix(dapp): fix connectToAddressDialog checkbox

### LINKED ISSUE #734: Make connectToAddressDialog checkbox clickable
Image

Make panel clickable, not only checkbox

### PR DESCRIPTION
**Pull request by KeitoTadashi**
fixes #734

### CODE REVIEW

**Review by marc2332 — APPROVED** [review]

File: dapp/src/components/dialogs/ConnectToAddressDialog.tsx [hunk 1]
```diff
@@ -242,7 +242,14 @@ export function ConnectToAddressDialog({ name, setOpen }: ConnectToAddressDialog
                                     </div>
                                     <Panel bgColor="bg-names-neutral-10">
                                         <div className="flex flex-col rounded-lg p-md gap-y-md">
-                                            <div className="flex flex-row items-start gap-x-md">
+                                            <div
```
Comment (panteleymonchuk) [inline dapp/src/components/dialogs/ConnectToAddressDialog.tsx:245]: I'd propose to update Panel a bit

```
<Panel bgColor="bg-names-neutral-10">
                                        <div className="flex flex-col rounded-lg gap-y-md">
                                            <div
                                                className={clsx(
                                                    'flex flex-row items-start gap-x-md p-md',
                                                    disableEdit || !isTargetingCurrentAddress
                                                        ? 'cursor-not-allowed'
                                                        : 'cursor-pointer',
                                                )}
                                                onClick={() => {
                                                    if (!disableEdit && isTargetingCurrentAddress) {
                                                        setEditIsDefaultName(!editIsDefaultName);
                                                    }
                                                }}
                                            >
                                                <div className=" flex flex-col gap-y-xxs">
                                                    <span className="text-title-md text-names-neutral-100">
                                                        Set as Display name
                                                    </span>
                                                    <span className="text-body-md text-names-neutral-90">
                                                        Use Name publicly across the web instead of
                                                        current address.
                                                    </span>
                                                </div>
                                                <Checkbox
                                                    isChecked={editIsDefaultName}
                                                    isDisabled={
                                                        disableEdit || !isTargetingCurrentAddress
                                                    }
                                                    onCheckedChange={(checked) =>
                                                        setEditIsDefaultName(
                                                            !!checked.target.checked,
                                                        )
                                                    }
                                                />
                                            </div>
                                            {editIsDefaultName && (
                                                <div className="px-md pb-md">
                                                    <Panel hasBorder bgColor="bg-names-neutral-10">
                                                        <div className="flex flex-col items-center gap-y-xxs py-md px-xs">
                                                            <span className="text-title-lg text-names-neutral-100 w-full text-center">
                                                                <TruncatedNameWithTooltip
                                                                    name={name}
                                                                    tooltipPosition={
                                                                        TooltipPosition.Top
                                                                    }
                                                                />
                                                            </span>
                                                            <Chip
                                                                label={formatAddress(
                                                                    account?.address || '',
                                                                )}
                                                                trailingElement={
                                                                    <Copy className="w-4 h-4" />
                                                                }
                                                                onClick={copyAddressToClipboard}
                                                                type={ChipType.Elevated}
                                                            />
                                                        </div>
                                                    </Panel>
                                                </div>
                                            )}

                                            {showAddressWarning && (
                                                <InfoBox
                                                    type={InfoBoxType.Warning}
                                                    style={InfoBoxStyle.Default}
                                                    icon={<Warning />}
                                                    title="Address has a linked name!"
                                                    supportingText="Continuing will override the previous address's name"
                                                />
                                            )}
                                        </div>
                                    </Panel>
```
                                    
Points why it might work better:
- show to user that clicking now allowed
- show to user that clicking checkbox is able to click (to whole block)



https://github.com/user-attachments/assets/29cd7b36-f225-433a-9466-62a5fe9f0b5a

**Review by brancoder — APPROVED** [review]
LGTM

**Review by panteleymonchuk — APPROVED** [review]
