### PR TITLE
fix(dapp): close context menu after clicking an option

### LINKED ISSUE #464: Close ContextMenu when an option is clicked
We should probably close the context menu when any of its options are clicked, otherwise it requires a second click to close it, which is kinda weird
Image

### PR DESCRIPTION
**Pull request by KeitoTadashi**
fixes #464

### CODE REVIEW

**Review by msarcev — APPROVED** [review]

**Review by Juligs — APPROVED** [review]

File: dapp/src/components/ContextMenu.tsx [hunk 1]
```diff
@@ -28,7 +35,14 @@ export function ContextMenuDropdown({ visible, position, options, dropdownRef }:
                 {options
                     .filter((option) => !option.isHidden)
                     .map((item, index) => (
-                        <ListItem key={index} {...item} />
+                        <ListItem
+                            key={index}
+                            {...item}
+                            onClick={() => {
+                                item.onClick?.();
+                                closeMenu();
```
Comment (VmMad) [inline dapp/src/components/ContextMenu.tsx]: I think this should be handled by the item.onClick so that this component doesn't depend on functions passed from the parents

File: dapp/src/components/buttons/ContextMenuButton.tsx [hunk 2]
```diff
@@ -24,6 +25,7 @@ export function ContextMenuButton({ options }: ContextMenuButtonProps) {
                 position={position}
                 options={options}
                 dropdownRef={dropdownRef}
+                closeMenu={closeMenu}
```
Comment (VmMad) [inline dapp/src/components/buttons/ContextMenuButton.tsx]: Instead of passing this props you can map the options and toggle the menu directly:
```tsx
    options={options.map((option) => ({
                    ...option,
                    onClick: () => {
                        option.onClick?.();
                        toggleMenu();
                    },
                }))}
```

File: dapp/src/components/buttons/ContextMenuButton.tsx [hunk 3]
```diff
@@ -13,7 +13,8 @@ interface ContextMenuButtonProps {
 }
 
 export function ContextMenuButton({ options }: ContextMenuButtonProps) {
-    const { isVisible, position, toggleMenu, dropdownRef, triggerRef } = useNameContextMenu();
+    const { isVisible, position, toggleMenu, closeMenu, dropdownRef, triggerRef } =
```
Comment (VmMad) [inline dapp/src/components/buttons/ContextMenuButton.tsx]:
```suggestion
    const { isVisible, position, toggleMenu, dropdownRef, triggerRef } =
```

File: dapp/src/components/ContextMenu.tsx [hunk 4]
```diff
@@ -13,9 +13,16 @@ interface ContextMenuProps {
     position: { top: number; left: number };
     options: MenuListItem[];
     dropdownRef: (el: HTMLDivElement | null) => void;
+    closeMenu: () => void;
```
Comment (VmMad) [inline dapp/src/components/ContextMenu.tsx]:
```suggestion
```

File: dapp/src/components/ContextMenu.tsx [hunk 5]
```diff
@@ -13,9 +13,16 @@ interface ContextMenuProps {
...
 }
 
-export function ContextMenuDropdown({ visible, position, options, dropdownRef }: ContextMenuProps) {
+export function ContextMenuDropdown({
+    visible,
+    position,
+    options,
+    dropdownRef,
+    closeMenu,
```
Comment (VmMad) [inline dapp/src/components/ContextMenu.tsx]:
```suggestion
```

File: dapp/src/app/(protected)/my-names/components/NamePanelTile.tsx [hunk 6]
```diff
@@ -88,6 +89,7 @@ export function NamePanelTile({
                 position={position}
                 options={menuOptions}
                 dropdownRef={dropdownRef}
+                closeMenu={closeMenu}
```
Comment (VmMad) [inline dapp/src/app/(protected)/my-names/components/NamePanelTile.tsx]: this can be left the same as before by mapping the options directly
```suggestion
```

**Review by VmMad — CHANGES_REQUESTED** [review]

**Review by VmMad — APPROVED** [review]
