### PR TITLE
fix(dapp): Add grace period

### LINKED ISSUE #372: Add grace period when renewing a root name

### PR DESCRIPTION
**Pull request by KeitoTadashi**
fixes #372 

https://github.com/iotaledger/iota-names/issues/250

### CODE REVIEW

File: dapp/src/lib/utils/names.ts [hunk 1]
```diff
@@ -1,14 +1,17 @@
...
+import { GRACE_PERIOD_MS, isSubName, NameRecord } from '@iota/iota-names-sdk';
 
 import { RegistrationNft } from '@/hooks';
 
 export function isNameRecordExpired(nameRecord: NameRecord) {
     return nameRecord.expirationTimestampMs < Date.now();
 }
 
+export function isNameRecordExpiredWithGracePeriod(nameRecord: NameRecord) {
+    return nameRecord.expirationTimestampMs < Date.now() + GRACE_PERIOD_MS;
```
Comment (msarcev) [inline dapp/src/lib/utils/names.ts]: 1. I think `isGracePeriodExpired` is a clearer name.
2. This logic looks incorrect to me 🤔 `return nameRecord.expirationTimestampMs + GRACE_PERIOD_MS < Date.now();` makes more sense and it's also clearer.
Wdyt ?

**Review by msarcev — CHANGES_REQUESTED** [review]

File: dapp/src/lib/utils/names.ts (hunk 1 above)
Comment (marc2332) [reply dapp/src/lib/utils/names.ts]: Yes, I agree with mario too

Comment (KeitoTadashi) [reply dapp/src/lib/utils/names.ts]: agree

**Review by msarcev — APPROVED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]
What about the call of `isNameRecordExpired` in `CreateSubnameDialog.tsx` ? Is that not needed there as well? Only in renew?

**Review by marc2332 — APPROVED** [review]
